- name: "Reset the kubeadms components"
  shell: "kubeadm reset --force"
  register: reset_cluster

- name: "Join to the kubernetes cluster"
  when: reset_cluster is succeeded
  shell: |
    kubeadm join --token {{ token }} \
                 --discovery-token-unsafe-skip-ca-verification \
                 {{ kubernetes_api }}:6443
  register: join_cluster
