- name: "Setup /etc/hosts"
  blockinfile:
    path: /etc/hosts
    marker: "<!-- {mark} ANSIBLE MANAGED BLOCK -->"
    block: |
      10.0.0.10 lb lb.k8s.local
      10.0.0.21 master1 master1.k8s.local
      10.0.0.22 master2 master2.k8s.local
      10.0.0.23 master3 master3.k8s.local
      10.0.0.31 worker1 worker1.k8s.local
      10.0.0.32 worker2 worker2.k8s.local
      10.0.0.33 worker3 worker3.k8s.local

- name: "Set authorized key for user Vagrant"
  authorized_key:
    user: vagrant
    state: present
    key: "{{ lookup('file', '../key.pub') }}"

- name: "Update all the packages"
  yum:
    name: "*"
    state: latest

- name: check if reboot is required
  shell: needs-restarting -r
  failed_when: false
  register: reboot_required
  changed_when: false

- when: reboot_required.rc != 0
  block:
    - name: reboot the server
      reboot:
