- name: "Reset the kubeadm components"
  shell: "kubeadm reset --force"
  register: reset_cluster

- name: "Configure kubeadm config folder"
  file:
    path: "{{ kubeadm_config_dir }}"
    owner: root
    group: root
    state: directory

- name: "Copy kubeadm-config.yaml file"
  template:
    src: kubeadm-config.yaml.j2
    dest: "{{ kubeadm_config_dir }}/kubeadm-config.yaml"
    owner: root
    group: root

- name: "Init Kubernetes cluster"
  when: reset_cluster is succeeded
  shell: |
    kubeadm init --config={{ kubeadm_config_dir }}/kubeadm-config.yaml \
    --experimental-upload-certs \
    --certificate-key {{ certificate_key }} 
  register: init_cluster

- name: "Create Kubernetes config directory"
  file:
    path: ".kube/"
    state: directory

- name: "Copy admin.conf to Home directory"
  when: init_cluster is succeeded
  copy:
    src: "{{ kubeadmin_config }}"
    dest: ".kube/config"
    owner: "{{ ansible_user | default(ansible_user_id) }}"
    group: "{{ ansible_user | default(ansible_user_id) }}"
    mode: 0755
    remote_src: true

- name: "Fetch admin.conf to local system"
  fetch:
    src: /etc/kubernetes/admin.conf
    dest: buffer/admin.conf
    flat: true

- name: "Deploy Canico network plugin"
  when: init_cluster is succeeded
  shell: |
    kubectl --kubeconfig={{ kubeadmin_config }} apply -f https://docs.projectcalico.org/v3.3/getting-started/kubernetes/installation/hosted/rbac-kdd.yaml
    kubectl --kubeconfig={{ kubeadmin_config }} apply -f https://docs.projectcalico.org/v3.3/getting-started/kubernetes/installation/hosted/kubernetes-datastore/calico-networking/1.7/calico.yaml

- name: "Get the patch to Calico plugin to use new POD CIDR: {{ pod_network_cidr }}"
  template:
    src: calico-patch.yaml.j2
    dest: /tmp/calico-patch.yaml
    owner: root
    group: root

- name: "Patch Calico plugin"
  shell: |
    kubectl --kubeconfig={{ kubeadmin_config }} patch ds calico-node -n kube-system --patch "$(cat /tmp/calico-patch.yaml)"

- name: "Pause the installation before proceed with the other controllers configuration"
  pause:
    minutes: 1
  when: init_cluster is succeeded
