- name: "Check if kubeadm was already configured"
  stat:
    path: "/etc/kubernetes/pki/ca.key"
  register: kubeadm_ca

- name: "Init cluster if not created"
  include_tasks: init.yml
  when: not kubeadm_ca.stat.exists
  run_once: yes

- name: "Enable and check kubelet service"
  systemd:
    name: kubelet
    daemon_reload: yes
    state: started
    enabled: yes
  register: started_kubelet
