---
- name: "Setup the kubernetes master instance"
  hosts: master
  gather_facts: yes
  become: yes

  roles:
    - k8s-setup-master

- name: "Setup the kubernetes controller instances"
  hosts: controllers
  gather_facts: yes
  become: yes
  serial: 1

  roles:
    - k8s-setup-controllers
